### ISSUE TITLE
Push to local registry with port

### ISSUE THREAD

**Issue by WestleyK** [ryanfowler/gopack#78]
Hi, how do I push to a local registry with a specific port? Like `localhost:5000`. If I specify that with the `-r` flag it returns this error:
```
Error: push: parsing repository "localhost:5000": repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: localhost:5000
```

**Comment by ryanfowler** [comment]
Hi! You should be able to specify a port in the repository URL. Unfortunately, I think that error is misleading. The problem with `localhost:5000` is that is doesn't actually specify a repository name. E.g. `localhost:5000/name`

**Comment by WestleyK** [comment]
That did the trick, thank you :+1:
